# We could verify the AllStar image with something like:
#   cosign verify ghcr.io/ossf/allstar:v4.0-busybox \
#     --certificate-identity-regexp  "https://github.com/ossf/allstar/.github/workflows/release.yaml"
#     --certificate-oidc-issuer https://token.actions.githubusercontent.com
# but it's a fairly uninteresting verification since it only shows the image was
# generated through GitHub Actions, not signed by one of the committers.
# More: https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/
---
name: GSA-TTS AllStar Enforcement Action

# See https://github.com/GSA-TTS/.allstar/blob/main/ADMIN.md for information
# on setup and administration of this GitHub Action.

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

env:
  ARTIFACT_DIR: /tmp/artifacts

jobs:
  scan:
    runs-on: ubuntu-latest
    # Use chainguard/busybox based image - It has a tail for entrypoint
    container:
      # specifying allstar by sha since tags are mutable. we don't verify the signature (see above)
      image: ghcr.io/ossf/allstar@sha256:f2d3dcbb6eff6940164df8fc900211968e2f07def4248208eb86bfb16c642fcf # v4.4-busybox
      # Running as root within unprivileged container does not violate STIGs, etc.
      options: --user root
    environment: prod
    steps:
      - name: Create Artifact Directory
        run: mkdir $ARTIFACT_DIR
      - name: Run AllStar Policy Check
        env:
          # Ping open issues every week (168 hours)
          NOTICE_PING_DURATION_HOURS: 168
          DO_NOTHING_ON_OPT_OUT: true # consistent with https://github.com/ossf/allstar/blob/main/app-prod.yaml#L12
          ALLSTAR_LOG_LEVEL: info
          KEY_SECRET: direct
          APP_ID: ${{ vars.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        # AllStar emits logs on stderr, not stdout
        run: |
          /ko-app/allstar -once > >(tee -a $ARTIFACT_DIR/allstar.out) 2> >(tee -a $ARTIFACT_DIR/allstar.log >&2);
      - name: Archive AllStar Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # @4.6.2
        with:
          name: allstar-scan
          path: ${{ env.ARTIFACT_DIR }}

  analyze:
    runs-on: ubuntu-latest
    needs: scan
    environment: prod
    steps:
      - name: Download scan artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # @4.3.0
        with:
          name: allstar-scan
      - name: Make artifacts directory
        run: mkdir $ARTIFACT_DIR
      - name: Summarize Results by Check
        run: |
          grep '^{' $GITHUB_WORKSPACE/allstar.log |
            jq --slurp '[.[] | select(.enabled == true and .message == "Policy run result.") ] |
              group_by(.area) | map({
                area: .[0].area,
                summary: {
                  pass_count: map(select(.result == true)) | length,
                  fail_count: map(select(.result == false)) | length,
                  passed: map(select(.result == true)| .repo),
                  failed: map(select(.result == false)| .repo)
                }
              })' |
            tee $ARTIFACT_DIR/scan_results_by_check.json
      - name: Output Scan Results by Check to Step Summary
        run: |
          echo '## Scan Results by Check' >> $GITHUB_STEP_SUMMARY
          SCAN_RESULTS=$(cat $ARTIFACT_DIR/scan_results_by_check.json)
          echo "$SCAN_RESULTS" | jq -r '.[] | "\n<details>\n<summary>\(.area) - Pass: \(.summary.pass_count), Fail: \(.summary.fail_count)</summary>\n\n| Pass Count | Fail Count | Passed | Failed |\n| --- | --- | --- | --- |\n| \(.summary.pass_count) | \(.summary.fail_count) | \(.summary.passed | join(", ")) | \(.summary.failed | join(", ")) |\n\n</details>\n"' >> $GITHUB_STEP_SUMMARY
      - name: Summarize Results by Repository
        run: |
          grep '^{' $GITHUB_WORKSPACE/allstar.log |
            jq --slurp '[.[] | select(.enabled == true and .message == "Policy run result.") ] |
              group_by(.repo) | map({
                repository: .[0].repo,
                summary: {
                  pass_count: map(select(.result == true)) | length,
                  fail_count: map(select(.result == false)) | length,
                  passed: map(select(.result == true)| .area),
                  failed: map(select(.result == false)| .area)
                }
              })' |
            tee $ARTIFACT_DIR/scan_results_by_repo.json
      - name: Output Scan Results by Repository to Step summary
        run: |
          echo '## Scan Results by Repository' >> $GITHUB_STEP_SUMMARY
          SCAN_RESULTS_REPO=$(cat $ARTIFACT_DIR/scan_results_by_repo.json)
          echo "$SCAN_RESULTS_REPO" | jq -r '.[] | "\n<details>\n<summary>\(.repository) - Pass: \(.summary.pass_count), Fail: \(.summary.fail_count)</summary>\n\n| Pass Count | Fail Count | Passed | Failed |\n| --- | --- | --- | --- |\n| \(.summary.pass_count) | \(.summary.fail_count) | \(.summary.passed | join(", ")) | \(.summary.failed | join(", ")) |\n\n</details>\n"' >> $GITHUB_STEP_SUMMARY
      - name: Archive AllStar Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # @4.6.2
        with:
          name: allstar-results
          path: ${{ env.ARTIFACT_DIR }}
