---
name: Run AllStar Policy Check

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use my chainguard/busybox based image - It has a tail.
    container: ghcr.io/pauldoomgov/allstar:v3.0-busy
    environment: prod
    steps:
      - name: Run Once
        env:
          APP_ID: ${{ vars.APP_ID }}
          KEY_SECRET: ${{ vars.KEY_SECRET }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: /ko-app/allstar -once
