---
name: Run AllStar Policy Check

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use my chainguard/busybox based image - It has a tail.
    container: ghcr.io/pauldoomgov/allstar:v3.0-busy
    environment: prod
    steps:
      - name: Run Once
        run: /ko-app/allstar once

