---
name: AllStar Enforcement Action

# See https://github.com/GSA-TTS/.allstar/blob/main/ADMIN.md for information
# on setup and administration of this GHA.

on:
  push:
    branches:
      - main
  schedule:
    - cron: '7 * * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use chainguard/busybox based image - It has a tail.
    container: ghcr.io/ossf/allstar:v4.0-busybox
    environment: prod
    steps:
      - name: Run AllStar Policy Check
        env:
          KEY_SECRET: direct
          APP_ID: ${{ vars.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: /ko-app/allstar -once
