---
name: AllStar Enforcement Action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 * * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use my chainguard/busybox based image - It has a tail.
    container: ghcr.io/ossf/allstar:v4.0-busybox
    environment: prod
    steps:
      - name: AllStar Enforce
        env:
          APP_ID: ${{ vars.APP_ID }}
          KEY_SECRET: ${{ vars.KEY_SECRET }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: /ko-app/allstar -once
