---
name: AllStar Enforcement Action

# See https://github.com/GSA-TTS/.allstar/blob/main/ADMIN.md for information
# on setup and administration of this GHA.

on:
  push:
    branches:
      - main
  schedule:
    - cron: '7 * * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use chainguard/busybox based image - It has a tail.
    container: ghcr.io/ossf/allstar:v4.0-busybox
    environment: prod
    steps:
      - name: Create Artifact Directoy
        run: mkdir /home/nonroot/artifacts
      - name: Run AllStar Policy Check
        env:
          # Ping open issues every week (168 hours)
          NOTICE_PING_DURATION_HOURS: 168
          DO_NOTHING_ON_OPT_OUT: true # consistent with https://github.com/ossf/allstar/blob/main/app-prod.yaml#L12
          ALLSTAR_LOG_LEVEL: info # use debug when needed.
          KEY_SECRET: direct
          APP_ID: ${{ vars.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: /ko-app/allstar -once | tee /home/nonroot/artifacts/allstar-report.txt
      - name: Archive AllStar Results
        uses: actions/upload-artifact@v3
        with:
          name: allstar-artifacts
          path: /home/nonroot/artifacts/

