---
name: Run AllStar Policy Check

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    container: ghcr.io/ossf/allstar:v3.0
    environment: prod
    steps:
      - name: Run Once
        run: |
          once

